---
title: 'Tidy Tuesday #9'
author: "Jocelyn Martinez Rico"
date: "12/21/2023"
output:
 prettydoc::html_pretty:
    theme: hpstr
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Introduction

My Tidy Tuesday submission #9 on Holiday Episodes from TidyTuesday Repository 2023-12-19 data.

# Load libraries 
```{r}
library(here)
library(tidyverse)
library(readr)
library(rcartocolor)
library(showtext)
library(ggplot2)
library(dplyr)
library(patchwork)
```

# Load data
```{r}
ep_genres <- read_csv(here("Tidy_Tuesday_9/data","holiday_episode_genres.csv"))
episodes <- read_csv(here("Tidy_Tuesday_9/data","holiday_episodes.csv"))

glimpse(ep_genres)
glimpse(episodes)

view(ep_genres)
view(episodes)
```

# Data clean-up/wrangling
```{r}
#For genres data set
genre_counts <- ep_genres %>%
  group_by(genres) %>%
  summarize(count = n()) #counts the occurrences of each genre

top_genres <- head(genre_counts[order(-genre_counts$count), ], 10) #gets the top 5 recurring genres

print(top_genres) #displays top 10
```

```{r}
#For episodes data set

filtered_episodes <- episodes %>% # Selecting specific variables
  select(parent_primary_title, parent_title_type, average_rating, parent_genres, original_title)

titles_to_search <- c("The Nanny", "Friends", "The Vampire Diaries", "George Lopez", "Modern Family") # Titles to search for

search_results <- filtered_episodes %>% filter(parent_primary_title %in% titles_to_search | original_title %in% titles_to_search) # Filtering based on the selected titles

print(search_results) # Display the search results

highest_rated_episodes <- search_results %>%
  group_by(parent_primary_title) %>%
  slice_max(order_by = average_rating, n = 1) #takes highest rated episode from search results

print(highest_rated_episodes) # Display the highest-rated episodes for each title
```

#Plotting the data
```{r}
font_add_google(name = "Lora",   # Name of the font on the Google Fonts site
                family = "lora") # Name you want to use to call the font
showtext_auto() #adds font
```

#Plot for Top 10
```{r}
xmas <- c("#6d0006", "#a91c24", "#e3d1c3", "#87a447", "#893119", "#374949", "#4f764a", "#96aeba", "#ce1f26", "#21406c")

t10 <- top_genres %>%
  ggplot(aes(x = genres,
             y = count,
             fill = genres)) +
  geom_bar(stat = "identity") +
  labs(x = "Genres",
       y = "Frequency of TV Episodes",
       fill = "Genres") + #Sets color
  theme_bw() + #theme for background
  theme(text = element_text(family = "lora"), #Adds font to plot
        axis.text.x = element_text(angle = 45, hjust = 1)) + #Creates angled axes
  scale_fill_manual("Genres:", values = xmas) #Fills bars with colors from xmas color set
t10
```
#Plot for highest-rated episodes for selected titles
```{r}
# Check unique values in parent_primary_title
unique_values <- unique(highest_rated_episodes$parent_primary_title)
print(unique_values)

# Check the number of unique values
num_unique_values <- length(unique_values)
print(num_unique_values)

# Check the structure of highest_rated_episodes
str(highest_rated_episodes)
```

```{r}
# Data frame for colors
cshows <- c("#c66a81", "#6b070f", "#797e84", "#d0000e", "#233329")

# Plot for episodes
hr_ep <- highest_rated_episodes %>%
  ggplot(aes(x = parent_primary_title, 
             y = average_rating, 
             fill = parent_genres)) +
  geom_point(size = 3) +
  geom_text(aes(label = original_title), vjust = -0.5, hjust = 1, check_overlap = TRUE) +  # Adjusted text label
  labs(title = "Average Rating of Highest Rated Episodes by Genre",
       x = "Parent Primary Title",
       y = "Average Rating",
       fill = "Parent Genres") +
  theme_bw() +
  theme(text = element_text(family = "lora"),  # Adds font to plot
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_manual(name = "Parent Genres", values = cshows)  # Set legend title consistently
hr_ep

```

